polygon-io/client-python

requirements.txt, setup.py
=> add deps to packaging logic

.drone.yml, setup.py
When trying to debug #16 I found that we were missing a required dep for install
=> adding requests as a dep for install

polygon/rest/client.py, rest-example.py
=> Make RESTful client a context manager and update example code

setup.py
=> chore[setup.py]: Relax install_requires

polygon/rest/models/definitions.py
Addresses feedback presented in #44
=> fix open close defintions

polygon/rest/aggs.py, polygon/rest/models/aggs.py, polygon/rest/trades.py
Since we now have types for `HTTPResponse`, use it!
=> add better types

.github/workflows/release.yml, poetry.lock, pyproject.toml
Not the most elegant, but the next release of poetry should fix this...
=> setup releasing on pushing a v* tag

polygon/websocket/__init__.py
Same fix as #155 but for websockets
=> add certifi for wss

README.md, docs/source/Getting-Started.rst, docs/source/WebSocket.rst, polygon/websocket/__init__.py, websockets-example.py
Simple sync and complicated async!
=> make websockets have 2 apis

examples/websocket/crypto.py, polygon/websocket/models/models.py
=> cryptotrade: rename sym to pair

examples/rest/financials.py, polygon/rest/models/tickers.py, test_rest/test_tickers.py
We should find a way to check more of these...
=> fix financials and add example

examples/rest/raw-get.py, examples/rest/raw-list.py, examples/rest/simple-get.py, examples/rest/simple-list.py, polygon/__init__.py, polygon/rest/base.py
Also make them work with free tier.
=> make examples simpler

examples/rest/financials.py, polygon/rest/reference.py
Closes #179
Param is in our docs and works: https://polygon.io/docs/stocks/get_v2_reference_news
=> add limit param to financials

docs/source/vX.rst, polygon/rest/__init__.py, test_rest/test_financials.py
=> lowercase vx

polygon/__init__.py
For convenience instead of `pip show polygon-api-client`.
=> add module __version__

polygon/rest/base.py
=> String Replacement Issue Fix

docs/source/Exceptions.rst, polygon/__init__.py, polygon/exceptions.py, polygon/rest/base.py, polygon/websocket/__init__.py
Users would like to not have to catch a generic "Exception"
=> Specific exceptions

polygon/rest/models/contracts.py
=> Fix OptionsContract model

.polygon/websocket.json
=> update ws spec

polygon/rest/snapshot.py
=> Fix locale for crypto snapshot

.polygon/websocket.json, polygon/websocket/models/models.py
=> add indicators to ws equity model

polygon/rest/trades.py
=> Fix docstring

examples/websocket/crypto.py, polygon/websocket/__init__.py, polygon/websocket/models/__init__.py, polygon/websocket/models/common.py, polygon/websocket/models/models.py
=> Parse crypto aggs

polygon/rest/quotes.py, polygon/rest/reference.py, polygon/rest/trades.py, polygon/rest/vX.py
=> improve limit description

.polygon/rest.json, .polygon/rest.py, Makefile
We need to add this script to pull and format the full open api spec correctly. I changed the diff checker a while back but forgot to update this make command.
=> update make rest spec

examples/websocket/latency.py, polygon/websocket/__init__.py
Closes #293
Closes #294
Bonus example to measure latency/
=> Fixes by at-cf

.polygon/rest.json
dupe of this [PR](https://github.com/polygon-io/client-go/pull/195). closes #307.
=> update rest spec

README.md
=> Set issue deadline of 3w

.polygon/websocket.json, polygon/websocket/models/models.py
=> Add new trf fields to EquityTrade and EquityQuote websocket models

polygon/rest/aggs.py
See this issue for what is being resolved: https://github.com/polygon-io/client-python/issues/349
=> Updated get_aggs docstring to change _from to from_

polygon/rest/summaries.py
Addressing [ticket](https://app.zenhub.com/workspaces/backend-6042935fc77665000f50780e/issues/gh/polygon-io/backend/842)
Adding options param to get_summaries function.
=> options param added to get_summaries

README.md, polygon/rest/summaries.py
Moving Launchpad section below web sockets.
=> Update readme launchpad

.polygon/rest.json, polygon/rest/vX.py
Addressing [ticket](https://app.zenhub.com/workspaces/backend-6042935fc77665000f50780e/issues/gh/polygon-io/backend/794)
=> financial update limit doc 1 to 10

README.md
Added link to blog that has the demo videos.
=> Updated getting started section

.polygon/rest.json
These are spelling/example updates and do not require any updates to the python client library outside just updating the spec file.
=> Spec spelling/examples updates

examples/websocket/indices.py
Adding a example Indices example that works for streaming both aggregates and values.
=> Add indices.py ws example

polygon/rest/models/dividends.py
Fixed bug https://github.com/polygon-io/client-python/issues/494.
=> Add currency to dividends

examples/websocket/stocks-ws_extra.py
Updated the example so that the text is centre aligned for a nicer look.
=> Center text for better formatting

.polygon/websocket.json
Fixes https://github.com/polygon-io/client-python/issues/519. Updated websocket spec to latest release. No code updates needed.
=> Update WS value data label

polygon/rest/models/summaries.py
Fixes https://github.com/polygon-io/client-python/issues/524.
=> Added last_updated to get_summaries

polygon/rest/base.py
clean up old code that prevented https://github.com/polygon-io/client-python/issues/525 from working, fixes https://github.com/polygon-io/client-python/issues/528
=> Fix for http status codes to retry requests on

examples/websocket/crypto.py, examples/websocket/forex.py, examples/websocket/indices.py
Added dedicated forex websocket example script and update the indices example to add second aggs.
=> Add crypto, forex and indices agg sec examples

.polygon/rest.json
Fixes https://github.com/polygon-io/client-python/issues/558.
=> Updated spec

examples/websocket/fmv.py, polygon/websocket/models/__init__.py, polygon/websocket/models/models.py
FMV events were not being parsed correctly. Updated the event parsing code to flag FMV events as the correct type and get this parsed into the correct model. Also added an example.
=> Fix FMV ws model and added example"

.polygon/rest.json, .polygon/websocket.json
Fixes https://github.com/polygon-io/client-python/issues/570 and https://github.com/polygon-io/client-python/issues/571. No code changes needed. The rest spec was updated to make a few descriptions clearer. The websocket spec was updated to add forex and crypto second aggs. The code/examples already exist for these updates.
=> Spelling and ws agg sec updates

examples/tools/async_websocket_rest_handler/async_websocket_rest_handler.py
Improved efficiency by creating only one RESTClient instance in ApiCallHandler, avoiding repeated setups for each API call.
=> Improved efficiency of async_websocket_rest_handler.py

.polygon/rest.json
Fixes https://github.com/polygon-io/client-python/issues/633. Updated rest spec to align with polygon spec. No code changes needed was just description changes.
=> Fixed rest spec

.polygon/rest.json
Fixes https://github.com/polygon-io/client-python/issues/650. No backend code changes needed since https://github.com/polygon-io/client-python/pull/652 already added CGI.
=> Updated spec with CGI and other misc updates

polygon/rest/aggs.py
=> Add type hinting for `datetime.date` objects to `get_grouped_daily_aggs`and `get_daily_open_close_agg`

.polygon/websocket.json
Fixes https://github.com/polygon-io/client-python/issues/738. No code changes needed this was just a documentation fix to remove an extra quote from the docs.
=> Updated ws spec to latest

examples/tools/hunting-anomalies/README.md, examples/tools/hunting-anomalies/aggregates_day/README.md, examples/tools/hunting-anomalies/build-lookup-table.py, examples/tools/hunting-anomalies/gui-lookup-table.py, examples/tools/hunting-anomalies/query-lookup-table.py
Added the readme and scripts for the Hunting Anomalies in the Stock Market blog tutorial.
=> Add Hunting Anomalies in the Stock Market scripts

poetry.lock, pyproject.toml
Updated the websockets & certifi dependencies so that we can support the latest versions.
=> Update websockets & certifi dependencies

polygon/websocket/models/common.py
Added IEX business to supported websockets.
=> Adds IEX business feed

polygon/websocket/models/models.py
Update to sync futures aggs with spec.
=> Sync futures aggs with latest spec
