polygon-io/client-python

polygon/rest/models/definitions.py
During an unmarshal the attribute_name was getting set to an empty string. Looks to be an order of operation issue w/ the string append.
=> Order of operation issue with _unmarshal_json_object

polygon/rest/client.py
This will throw a `requests.ConnectTimeout` if the timeout is passed before the server responds. I believe the default amount of retries is 3, but I haven't checked.
=> pass RESTClient a timeout in seconds

polygon/rest/client.py, polygon/rest/models/__init__.py, polygon/rest/models/definitions.py
I've added the new reference ticker endpoints and their corresponding types to the python client. I tested the functions myself and everything looks good AFAICT -- feel free to test it yourself.
=> New reference endpoints

polygon/rest/client.py, polygon/rest/models/__init__.py, polygon/rest/models/definitions.py
I added all of our missing endpoints and tested them manually. Everything's been tested. Here's output:
<details>
<summary>Output as YAML</summary>
```yaml
adjusted: true
count: 150
py/object: polygon.rest.models.definitions.CryptoGroupedDailyApiResponse
queryCount: 150
request_id: c9138b089a36e570227dafbe5f73d45b
results:
-   T: X:INKUSD
c: 0.00071701
h: 0.000895
l: 0.00069325
n: 74
o: 0.000895
t: 1602719999999
v: 114570
vw: 0.0008
resultsCount: 150
status: OK
adjusted: true
count: 1
py/object: polygon.rest.models.definitions.CryptoPreviousCloseApiResponse
queryCount: 1
request_id: 279ad14b79a220c438669c2ba6d3467f
results:
-   T: X:BTCUSD
c: 54894.03
h: 56500
l: 53770.9
n: 679915
o: 55077.4
t: 1619654399999
v: 44170.754370356175
vw: 54822.2037
resultsCount: 1
status: OK
ticker: X:BTCUSD …
```
=> Missing endpoints

polygon/rest/models/definitions.py
A previous update to the Swagger code created a bug due to the wrong names being put into the type mappings in `StocksEquitiesDailyOpenCloseApiResponse` under the REST models. See #69. 
After running the updated version of the client, I am able to run the user's code successfully:
```py
with RESTClient(os.environ['API_KEY']) as client:
resp = client.stocks_equities_daily_open_close("AAPL", "2018-03-02")
print(f"On: {resp.from_} Apple opened at {resp.open} and closed at {resp.close}")
```
Result:
```
On: 2018-03-02 Apple opened at 43.2 and closed at 44.0525
```
=> Fix StocksEquitiesDailyOpenCloseApiResponse type mappings

README.md
For free users, those of us just getting started with the client, the REST response 404s, because historical data back to 2018 is unavailable. A quick update of the docs prevents users who are just beginning with the client from receiving the following error:
```sh
python sample.py
Traceback (most recent call last):
File "<PATH>/sample.py", line 14, in <module>
main()
File "<PATH>/sample.py", line 9, in main
resp = client.stocks_equities_daily_open_close("AAPL", "2018-03-02")
File "<PYTHON_PATH>/lib/python3.9/site-packages/polygon/rest/client.py", line 128, in stocks_equities_daily_open_close
return self._handle_response("StocksEquitiesDailyOpenCloseApiResponse", endpoint, query_params)
File "<PYTHON_PATH>/lib/python3.9/site-packages/polygon/rest/client.py", line 35, in _handle_response …
```
=> Update README with more recent dates in examples

.github/workflows/test.yml, Makefile, poetry.lock, pyproject.toml, tests/mocks.py, tests/test_aggs.py
Use [httpretty](https://httpretty.readthedocs.io/en/latest/guides.html) and the builtin Python [unittest package](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp).
=> Add unittest

tests/mocks.py, tests/test_aggs.py
Not great that mocks have to be reinstalled for every test file, but better than what we had before (which was per-test).
=> Use setupclass for test setup

polygon/rest/aggs.py, polygon/rest/base.py, polygon/rest/models/trades.py, polygon/rest/trades.py, tests/test_aggs.py, tests/test_markets.py, tests/test_snapshots.py, tests/test_tickers.py, tests/test_trades.py
Fix these endpoints to return dataclasses instead of lists of dataclasses:
```
get_daily_open_close_agg
get_daily_open_close_agg
get_daily_open_close_agg
get_snapshot_option
get_snapshot_ticker
get_ticker_details
get_last_trade
get_last_trade_crypto
```
=> fix non-list return types

poetry.lock, polygon/rest/base.py, polygon/websocket/__init__.py, pyproject.toml
Also quick websocket test bugfix
=> User agent version

Makefile, examples/rest/raw-get.py, examples/rest/raw-list.py, examples/rest/simple-get.py, examples/rest/simple-list.py, examples/websocket/aggs.py, examples/websocket/async.py, examples/websocket/crypto.py, examples/websocket/raw.py, examples/websocket/simple.py
=> use kw arg names in examples

polygon/logging.py, polygon/rest/base.py, polygon/websocket/__init__.py, polygon/websocket/models/__init__.py, test_websocket/base_ws.py
Make logs more extensible. Keep existing api of `verbose`. Logger can still be overridden by consumers via `logging.getLogger('RESTClient')` or `logging.getLogger('WebsocketClient')`.
Logs look like this now:
```
2022-05-17 15:27:17,493 RESTClient DEBUG: _get /v2/aggs/ticker/AAPL/range/1/day/2022-04-04/2022-04-04 params {}
2022-05-17 15:29:30,465 WebSocketClient DEBUG: sub desired: T.AAPL
2022-05-17 15:29:30,466 WebSocketClient DEBUG: sub desired: T.AMZN
2022-05-17 15:29:30,466 WebSocketClient DEBUG: sub desired: T.*
2022-05-17 15:29:30,466 WebSocketClient DEBUG: sub undesired: T.*
2022-05-17 15:29:30,466 WebSocketClient DEBUG: closing
2022-05-17 15:29:30,466 WebSocketClient WARNING: no websocket open to close
```
=> Add Logger

README.md
Copy go and add a paragraph about dunder methods and types.
=> Versioning guide

polygon/rest/aggs.py
This will be inconsistent with other APIs that take a required market type parameter in the order of the URL... but oh well
=> add market type for grouped endpoint

.polygon/rest.json
=> update rest spec

polygon/rest/models/common.py, polygon/websocket/models/models.py
Forgot this in the last commit. Oops!
=> Add OTC websocket models

polygon/rest/models/contracts.py, test_rest/test_contracts.py
=> add contract type to models

.polygon/rest.json
No implementation change needed because aggs transactions are already ints. 
Closes #249
=> update rest specs

polygon/rest/reference.py, test_rest/mocks/v3/reference/tickers/AAPL&date=2020-10-01.json, test_rest/test_tickers.py
Fixes #320 
I put a second assert in the same test method, but happy to factor the expected response data out and create a second test method, if you prefer to follow the "one assertion per test" paradigm
=> include date param in get_ticker_details

polygon/rest/aggs.py
Running into a type error that doesn't seem like it should be an error, I'm assuming this return type should be iterable. Like other similar returns give a collection of data.
the comments below describe it as `List` so something is most definitely off.
`:return: List of grouped daily aggregates`
=> add iterator type to get_grouped_daily_aggs return

polygon/rest/models/tickers.py
[bug](https://github.com/polygon-io/client-python/issues/370) quick fix. ticker_suffix missing from ticker details
=> added ticker_suffix to TickerDetails model class

polygon/rest/base.py
There are two bugs https://github.com/polygon-io/client-python/issues/382 and https://github.com/polygon-io/client-python/issues/388 that have reported query filter extensions ("lt", "lte", "gt", "gte", "any_of") are not working as expected. Thanks to the debug work of `jakekdodd` it was easy to track down the source of the bug.
Examples of the malformed params being passed to the API before the fix:
- `expiration.date_gte`
- `strike.price_gte`
Examples of what these should look like:
- `expiration_date.gte`
- `strike_price.gte`
Example 1 - code to test (these should both get you the same result):
```python
from polygon import RESTClient
client = RESTClient()
foo = client.list_options_contracts(underlying_ticker='HCP', expiration_date_gte='2024-03-16', contract_type='call', …
```
=> Fix malformed query filter params

examples/rest/options-aggregates_bars.py, examples/rest/options-conditions.py, examples/rest/options-contract.py, examples/rest/options-contracts.py, examples/rest/options-daily_open_close.py, examples/rest/options-exchanges.py, examples/rest/options-last_trade.py, examples/rest/options-market_holidays.py, examples/rest/options-market_status.py, examples/rest/options-previous_close.py, examples/rest/options-quotes.py, examples/rest/options-snapshots_option_contract.py, examples/rest/options-snapshots_options_chain.py, examples/rest/options-technical_indicators_ema.py, examples/rest/options-technical_indicators_macd.py, examples/rest/options-technical_indicators_rsi.py, examples/rest/options-technical_indicators_sma.py, examples/rest/options-ticker_details.py, examples/rest/options-ticker_news.py, examples/rest/options-tickers.py, examples/rest/options-trades.py, examples/websocket/options-ws.py
Added code snippets for each Options API endpoint and real-time streaming via the websocket.
=> Added options demo scripts

polygon/rest/base.py
Enables gzip encoding for all HTTP requests, by adding the "Accept-Encoding: gzip" header to the request. Gzip encoding compresses the response body before sending it to the client, which reduces the size of the response and saves bandwidth.
Urllib3 supports gzip encoding out of the box. By default, urllib3 will automatically decode the gzip response if the server returns a compressed response. So, we are explicitly requesting gzip encoding via the request headers, by adding setting the Accept-Encoding header to gzip.
By enabling gzip encoding, we expect to see faster download times and reduced bandwidth usage for our users.
Server response headers without gzip:
```
Response headers:
Server: nginx/1.19.2
Date: Mon, 20 Mar 2023 20:40:30 GMT
Content-Type: application/json
Transfer-Encoding: …
```
=> Force gzip encoding for faster response and reduced bandwidth usage

polygon/rest/indicators.py
Indicators accepts the limit param but it was missing. So, added it for all four technical indicators.
=> Added limit param to Indicators

polygon/rest/models/markets.py
Added indices to return when calling market status.
Before:
MarketStatus(after_hours=False, currencies=MarketCurrencies(crypto='open', fx='open'), early_hours=True, exchanges=MarketExchanges(nasdaq='extended-hours', nyse='extended-hours', otc='extended-hours'), indicesGroups=None, market='extended-hours', server_time='2023-03-29T08:59:42-04:00')
After:
MarketStatus(after_hours=False, currencies=MarketCurrencies(crypto='open', fx='open'), early_hours=True, exchanges=MarketExchanges(nasdaq='extended-hours', nyse='extended-hours', otc='extended-hours'), indicesGroups=MarketIndices(s_and_p='open', societe_generale='open', msci='closed', ftse_russell='closed', mstar='open', mstarc='open', cccy='open', nasdaq='closed', dow_jones='closed'), market='extended-hours', …
=> Added indices to market status

docs/source/Aggs.rst, examples/rest/crypto-aggregates_bars.py, examples/rest/forex-aggregates_bars.py, examples/rest/indices-aggregates_bars.py, examples/rest/options-aggregates_bars.py, examples/rest/stocks-aggregates_bars.py, examples/rest/stocks-aggregates_bars_extra.py, examples/rest/stocks-aggregates_bars_highcharts.py
Updated the examples and documentation with agg pagination support. Users previously had to fetch aggregate data in smaller chunks to conform to the 50k API limit, however with the inclusion of automatic pagination, the client now seamlessly handles large data requests. This update greatly improves usability and efficiency when working with substantial datasets.
=> Updated Examples and Docs to Support Agg Pagination

README.md
Added filter params example to the readme. There have been a couple reported issues about this not working and I suspect it's a documentation issue. So, adding this example will hopefully solve the issue.
=> Update README.md with additional filter parameters section

examples/rest/universal-snapshot.py, polygon/rest/snapshot.py
This PR fixes the issue reported in [#476](https://github.com/polygon-io/client-python/issues/476), where the `market_type` parameter was incorrectly named and several other parameters were missing in the `list_universal_snapshots` method of the `SnapshotClient` class. The updates made in this PR align the code with the expected behavior and fixes a bug in universal snapshots retrieval by renaming the `market_type` parameter to `type` and adding the missing parameters `order`, `limit`, and `sort`. The corresponding example has also been updated to reflect these changes.
=> Fix parameter naming and add missing parameters in list_universal_snapshots

examples/rest/crypto-exchanges.py, examples/rest/crypto-market_holidays.py, examples/rest/crypto-snapshots_all_tickers.py, examples/rest/crypto-snapshots_gainers_losers.py, examples/rest/financials.py, examples/rest/forex-exchanges.py, examples/rest/forex-market_holidays.py, examples/rest/forex-snapshots_all_tickers.py, examples/rest/forex-snapshots_gainers_losers.py, examples/rest/indices-market_holidays.py, examples/rest/options-exchanges.py, examples/rest/options-market_holidays.py, examples/rest/options-ticker_news.py, examples/rest/stocks-aggregates_bars_extra.py, examples/rest/stocks-aggregates_bars_highcharts.py, examples/rest/stocks-exchanges.py, examples/rest/stocks-market_holidays.py, examples/rest/stocks-snapshots_all.py, examples/rest/stocks-snapshots_gainers_losers.py, examples/rest/stocks-ticker_news.py, examples/rest/stocks-trades_extra.py, examples/websocket/stocks-ws_extra.py, polygon/modelclass.py, polygon/rest/reference.py, test_rest/models/test_requests.py
PR https://github.com/polygon-io/client-python/pull/470 from dependabot is attempting to update poetry black from 22.12.0 to 23.7.0. However, the PR is failing the lint check because poetry black found a few issues. So, this PR fixes those lint issue then we can merge https://github.com/polygon-io/client-python/pull/470.
=> Fix linting for upgrade to poetry black 23.7.0

polygon/rest/base.py
Wrapped the JSON decoding process in a try-except to catch `ValueError`. In case of a decoding error, a log message is printed, and the function returns an empty list. Fixes https://github.com/polygon-io/client-python/issues/499.
=> Handle JSON decoding errors in _get and _paginate_iter

polygon/rest/base.py
=> Update http status codes to retry request on

polygon/rest/base.py
Added a retry on 499 error code. Reading the docs this seems like a request timeout issue where the connection gets closed. It seems like a special code for nginx similar to gateway timed out but on the client side where they close it after waiting too long. We should retry on this.
=> Retry on 499 status code

polygon/websocket/__init__.py
Fixes polygon-io/backend/1474. Tickers like `BRK.B` were not getting parsed correctly. Changed to logic to only split on the first period and then pass along everything else. https://github.com/polygon-io/client-python/pull/559 has another potential fix but I prefer this once since the overall intention is to split out the event topic and the ticker symbol.
I've tested this and it works as expected:
```
2023-11-27 13:56:19,066 WebSocketClient DEBUG: sub desired: T.BRK.B
2023-11-27 13:56:19,066 WebSocketClient DEBUG: connect: wss://socket.polygon.io/stocks
2023-11-27 13:56:19,432 WebSocketClient DEBUG: connected: [{"ev":"status","status":"connected","message":"Connected Successfully"}]
2023-11-27 13:56:19,432 WebSocketClient DEBUG: authing...
2023-11-27 13:56:19,517 WebSocketClient DEBUG: …
```
=> Fix websocket parse of tickers with periods

examples/tools/async_websocket_rest_handler/async_websocket_rest_handler.py, examples/tools/async_websocket_rest_handler/readme.md
An example script that demonstrates a non-blocking pattern for handling WebSocket streams and REST API calls in Python using asyncio. We're going to link to this from a blog tutorial.
=> Added example for async websocket and rest calls

README.md
Fixes https://github.com/polygon-io/client-python/issues/593.
Updated installation documentation to include a note on setuptools dependency, ensuring comprehensive guidance for all user environments. `setuptools` is a key package in Python used for building, distributing, and installing packages. It is not part of the Python Standard Library, but it is included with most Python distributions, such as the official Python distributions from python.org, Anaconda, and others.
For most users, especially those using Python distributions intended for application development and data science, setuptools will be pre-installed, making it seem like it's a default part of Python. However, in minimal or custom Python environments, setuptools might not be included by default and may need to be …
=> Update README.md with setuptools

examples/tools/docker/Dockerfile, examples/tools/docker/app.py, examples/tools/docker/readme.md
Added a Docker example that supports running the python `polygon-api-client` package within a container. This ensures a consistent and isolated environment. It includes a Dockerfile, example app, and documentation for easy setup and deployment.
=> Add Docker support for polygon-api-client usage example

README.md
Fixes https://github.com/polygon-io/client-python/issues/594.
This PR updates the Getting Started section to include a note on the limitations of free API keys and encourages upgrading for higher limits. It aims to enhance user awareness about potential throttling and improve their experience with proactive guidance.
=> Add API key usage note to Getting Started section

polygon/rest/base.py
Pull request for the issue I opened here: https://github.com/polygon-io/client-python/issues/631
=> Use ssl_context for HTTPS requests to avoid reading certificate files on every request

polygon/rest/models/markets.py
CBOE recently added the CGI (CBOE Global Indices) feed, and as a result it was added to the Market Status endpoint.
=> Add CGI to MarketIndices

README.md
=> Update README.md to remove LaunchPad

poetry.lock, polygon/websocket/__init__.py, pyproject.toml
Attempting to fix lint formatting issue with https://github.com/polygon-io/client-python/pull/658.
=> Update ws init lint formatting

.polygon/rest.json, examples/rest/stocks-related_companies.py, polygon/rest/models/tickers.py, polygon/rest/reference.py
Update client with [related companies](https://polygon.io/docs/stocks/get_v1_related-companies__ticker) support. This PR updates the spec, adds a `get_ticker_details` function, a `RelatedCompany` model class, and a working example. This also fixes https://github.com/polygon-io/client-python/issues/682 for the spec changes.
```python
from polygon import RESTClient
client = RESTClient()  # POLYGON_API_KEY environment variable is used
related_companies = client.get_related_companies("AAPL")
print(related_companies)
```
```
$ python examples/rest/stocks-related_companies.py
[
RelatedCompany(ticker="MSFT"),
RelatedCompany(ticker="GOOGL"),
RelatedCompany(ticker="AMZN"),
RelatedCompany(ticker="GOOG"),
RelatedCompany(ticker="TSLA"),
RelatedCompany(ticker="NVDA"),
RelatedCompany(ticker="META"), …
```
=> Added support for related companies endpoint

README.md, polygon/rest/base.py
This PR updates the method for retrieving the version number of the `polygon-api-client` package. It replaces the use of `pkg_resources` from `setuptools` with `importlib.metadata`, which is part of the standard library in Python 3.8 and newer.
- Removed `import pkg_resources` and replaced it with `from importlib.metadata import version, PackageNotFoundError`.
- Updated the version retrieval logic to use `importlib.metadata.version` instead of `pkg_resources.require`.
- Reduces external dependency on `setuptools` which is deprecated and causing issues (https://github.com/polygon-io/client-python/issues/693 & https://github.com/polygon-io/client-python/issues/593)
- Utilizes the standard library, improving compatibility and reducing overhead.
=> Update base.py to remove setuptools and use standard library

examples/rest/raw-list.py
Fixed the example to have the correct params. You cannot pass date eq (`timestamp=`) with a less than (`timestamp.lt=`). It needs to be either or.
```
polygon.exceptions.BadResponse: {"status":"ERROR","request_id":"71f9a7ec439a46e7884c38c893daddcc","error":"failed to parse timestamp query params: query parameters cannot have the combination of equal and any other param gt, gte, lt, lte"}
```
Fixed the example to just pass the date.
=> Fix example to have correct params

polygon/rest/base.py
Reverts polygon-io/client-python#632.
On windows a couple users are reporting ssl error via https://github.com/polygon-io/client-python/issues/638. I want to revert this optimization to rule out the issue.
=> Revert "Use ssl_context for HTTPS requests to avoid reading certificate files on every request"

.polygon/rest.json, polygon/rest/models/tickers.py
Fixes https://github.com/polygon-io/client-python/issues/708.
This PR adds support for Ticker News Insights where it ranks mentioned tickers by sentiment (negative, neutral, or positive) and then provides the reasoning why.
Here's an example script:
```python
from polygon import RESTClient
from polygon.rest.models import (
TickerNews,
)
client = RESTClient()  # POLYGON_API_KEY environment variable is used
news = []
for n in client.list_ticker_news("MSFT", order="desc", limit=1000):
news.append(n)
for index, item in enumerate(news):
if isinstance(item, TickerNews):
print(item)
if index == 10:
break
```
You'll get a response object that now lists `insights` like the following:
```
TickerNews(
amp_url=None,
article_url="https://www.benzinga.com/news/24/07/39795029/googles-potential-23b-wiz-ac …
```
=> Added ticker news insights support

.polygon/rest.json, polygon/rest/models/dividends.py, polygon/rest/models/splits.py
Fixes https://github.com/polygon-io/client-python/issues/732.
Added unique Dividend and Split IDs.
=> Add dividend and split ids

polygon/rest/models/snapshot.py
We recently added `regular_trading_change` and `regular_trading_change_percent` to this response, which represents the change in the asset between its open and close.
=> Update Universal Snapshot 'session' model

examples/rest/economy-treasury_yields.py, examples/rest/stocks-short_interest.py, examples/rest/stocks-short_volume.py, polygon/rest/models/tickers.py, polygon/rest/vX.py
Adds support for latest beta endpoints.
Tested locally.
=> Adds IPOs, Short Interest/Volume, and Treasury Yields
